name: Delete CI models

on:
    workflow_dispatch:

env:
    DBT_PROFILES_DIR: ./
    DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
    DBT_TARGET: ci
    DBT_PR_ID: ${{ github.event.pull_request.number }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    clean-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
        
            - name: Install Dependecies
              run: |
                python3 -m pip install --upgrade pip
                pip3 install -r requirements.txt
        
            - name: Delete CI models
              run: |
                dbt deps
                dbt run-operation delete_ci_models --args "{ pr_id: $DBT_PR_ID, materialization: view }"
                dbt run-operation delete_ci_models --args "{ pr_id: $DBT_PR_ID, materialization: table }"