name: CI, Launch a dbt build

on:
    workflow_dispatch:

env:
    DBT_PROFILES_DIR: ./
    DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
    DBT_TARGET: ci
    DBT_PR_ID: ${{ github.event.pull_request.number }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    launch-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Install Dependecies
              run: |
                python3 -m pip install --upgrade pip
                pip3 install -r requirements.txt
            
            - name: Configure preproduction AWS creds
              run: |
                pip install awscli
            
            - name: Push Manifest to S3
              run: make pull-manifest ENV=dev
            
            - name: Launch dbt deffered with last manifest
              run: make run-ci
  